package com.jonoshields.driftwood.core.model

import com.jonoshields.driftwood.core.crypto.Hex
import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/** Pins the wire format against committed vectors, catching silent byte-level drift; after an intended change, copy `build/golden_messages.actual.tsv` over the committed file. */
class GoldenVectorsTest {

    private val resourcePath = "/golden_messages.tsv"
    private val sourcePath = "src/test/resources/golden_messages.tsv"

    /** Fixed inputs — no randomness, no clock, no environment. */
    private fun cases(): List<Pair<String, Message>> {
        val signer = Ed25519Signer(ByteArray(32) { it.toByte() })
        val author = signer.publicKey
        val rootId = MessageId.of(ByteArray(32) { (0xF0 - it).toByte() })
        val parentId = MessageId.of(ByteArray(32) { (it * 7).toByte() })

        return listOf(
            "root-empty-text" to
                MessageFactory.createRoot(author, "", 0L, signer),
            "root-ascii" to
                MessageFactory.createRoot(author, "hello", 1_700_000_000_000L, signer),
            "root-at-length-cap" to
                MessageFactory.createRoot(author, "a".repeat(MSG_MAX_CHARS), 1L, signer),
            "root-astral-plane" to
                MessageFactory.createRoot(author, "🜁🜂🜃🜄 alchemy", 2L, signer),
            "root-cjk" to
                MessageFactory.createRoot(author, "日本語のテキスト", 3L, signer),
            "root-max-timestamp" to
                MessageFactory.createRoot(author, "far future", Long.MAX_VALUE, signer),
            "reply-root-only" to
                MessageFactory.createReply(author, rootId, null, "reply without a parent", 4L, signer),
            "reply-root-and-parent" to
                MessageFactory.createReply(author, rootId, parentId, "reply with a parent", 5L, signer),
        )
    }

    private fun render(): String = buildString {
        appendLine("# Golden vectors for the canonical message format.")
        appendLine("# Generated by GoldenVectorsTest, which also writes the current output to")
        appendLine("# core/model/build/golden_messages.actual.tsv on every run.")
        appendLine("# Columns: name<TAB>preimageHex<TAB>idHex<TAB>signatureHex")
        cases().forEach { (name, message) ->
            append(name)
            append('\t')
            append(Hex.encode(CanonicalCodec.encode(message.body)))
            append('\t')
            append(message.id.toHex())
            append('\t')
            append(Hex.encode(message.signature))
            append('\n')
        }
    }

    @Test
    fun `wire format matches the committed golden vectors`() {
        val current = render()

        // Always write what this build actually produces, so a failure comes with the
        // replacement file already on disk rather than instructions to go and make one.
        val actual = File("build/golden_messages.actual.tsv")
        actual.parentFile.mkdirs()
        actual.writeText(current)

        val committed = javaClass.getResourceAsStream(resourcePath)?.bufferedReader()?.readText()
        assertTrue(
            "$sourcePath is missing. Copy ${actual.path} into place and review it.",
            committed != null,
        )
        assertEquals(
            "The wire format changed. If that was deliberate, copy ${actual.path} over " +
                "$sourcePath and review the diff — every existing message id in the " +
                "network changes with it.",
            committed,
            current,
        )
    }

    @Test
    fun `golden vectors verify`() {
        cases().forEach { (name, message) ->
            val result = MessageVerifier.verify(MessageCodec.encode(message))
            assertTrue("$name did not verify: $result", result is VerifyResult.Valid)
        }
    }
}
